apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-db
    spec:
      containers:
      - name: {{ .Chart.Name }}
        env: 
          - name: MARIADB_USER
            value: {{ .Values.db.dbUsername }}
          - name: MARIADB_PASSWORD
            value: {{ .Values.db.dbPassword }}
          - name: MARIADB_ROOT_PASSWORD
            value: {{ .Values.db.rootPassword }}
        image: {{ .Values.db.repository }}:{{ .Values.db.tag }}
        imagePullPolicy: {{ .Values.db.pullPolicy }}
        ports:
        - containerPort: {{ .Values.db.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-mariadb
spec:
  ports:
  - port: {{ .Values.db.port }}
    protocol: TCP
    targetPort: {{ .Values.db.port }}
  selector:
    app: {{ .Chart.Name }}-db