apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-controller
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-controller
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.controller.repository }}:{{ .Values.controller.tag }}
        pullPolicy: {{ .Values.controller.pullPolicy }}:
        ports:
        - containerPort: {{ .Values.controller.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  ports:
  - port: {{ .Values.controller.port }}
    protocol: TCP
    targetPort: {{ .Values.controller.port }}
  selector:
    app: {{ .Values.name }}-controller

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ .Values.name }}-service
          servicePort: {{ .Values.controller.port }}
