apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-{{ .Values.id }}-deployment
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-{{ .Values.id }}-controller
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-{{ .Values.id }}-controller
    spec:
      containers:
      - name: {{ .Chart.Name }}-{{ .Values.id }}
        image: {{ .Values.controller.repository }}:{{ .Values.controller.tag }}
        imagePullPolicy: {{ .Values.controller.pullPolicy }}
        ports:
        - containerPort: {{ .Values.controller.port }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.id }}-service
spec:
  ports:
  - port: {{ .Values.controller.port }}
    protocol: TCP
    targetPort: {{ .Values.controller.port }}
  selector:
    app: {{ .Chart.Name }}-{{ .Values.id }}-controller

---

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-{{ .Values.id }}-ingress
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ .Chart.Name }}-{{ .Values.id }}-service 
            port:
              number: {{ .Values.controller.port }} 
          {{- else }}
          serviceName: {{ .Chart.Name }}-{{ .Values.id }}-service 
          servicePort: {{ .Values.controller.port }} 
          {{- end }}